[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/bypass"
  to = "/.netlify/functions/bypass"
  status = 200

[[redirects]]
  from = "/api/links"
  to = "/.netlify/functions/links"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
